version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: your-database-host
      DB_NAME: electronics_shop
      DB_USER: your-db-user
      DB_PASS: your-db-password
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: electronics_shop
      POSTGRES_USER: your-db-user
      POSTGRES_PASSWORD: your-db-password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
